# Generated by Django 5.2.4 on 2025-07-24 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("rent", "Rent"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        default="food",
                        max_length=13,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
