# Generated by Django 5.2.4 on 2025-08-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_alter_addbudget_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addbudget",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 8, 5, 12, 37, 32, 463576, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
