# Generated by Django 5.2.4 on 2025-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addexpense",
            name="name",
        ),
        migrations.AddField(
            model_name="addexpense",
            name="exp_category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("rent", "Rent"),
                    ("entertainment", "Entertainment"),
                ],
                default="food",
                max_length=13,
            ),
        ),
    ]
