# Generated by Django 5.2.4 on 2025-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_addexpense_name_addexpense_exp_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="addexpense",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
