# Generated by Django 5.2.4 on 2025-07-22 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_addexpense_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="addexpense",
            name="exp_category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("rent", "Rent"),
                    ("entertainment", "Entertainment"),
                    ("other", "Other"),
                ],
                default="food",
                max_length=13,
            ),
        ),
    ]
