# Generated by Django 5.2.4 on 2025-07-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_otherexpense_alter_addexpense_exp_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtherExpense",
        ),
        migrations.AddField(
            model_name="addexpense",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
