# Generated by Django 5.2.4 on 2025-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_otherexpense_addexpense_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addexpense",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
