# Generated by Django 5.2.4 on 2025-07-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_addexpense_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addexpense",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
