# Generated by Django 5.2.4 on 2025-07-24 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_addexpense_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addexpense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
