# Generated by Django 5.2.4 on 2025-07-28 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_addexpense_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="addexpense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
