# Generated by Django 5.2.4 on 2025-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "business_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "freelance_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
