# Generated by Django 5.2.4 on 2025-07-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_addincome_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="addincome",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 29, 6, 39, 13, 766058, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
