# Generated by Django 5.2.4 on 2025-07-29 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0004_addincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addincome",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 29, 13, 20, 56, 933936, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
