# Generated by Django 5.2.4 on 2025-08-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_alter_addincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addincome",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 8, 5, 12, 37, 32, 461490, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
